### ISSUE TITLE
How to align the depth and cameras?

### ISSUE THREAD

**Issue by JiuTongBro** [wildrgbd/wildrgbd#2]
Hi. Thanks for your meaningful dataset!

However, I wonder how to align the depth and cameras. As you mentioned, the depth image is stored in meters/1000, or to say, millimeter. I suppose it is a little abnormal, as I checked the depth image of tha apple scene, and the maximum depth value of the foreground are usually near 25. So the depth of the foreground is 25mm?

According to the camera extrinsics, there are camera positions like [-0.4, -0.1, 0.3]. I suspect, they are measued by meters, and this time it looks correct (the radius of a real-life scene is usually measured by meters). But this assumption leads to inconsistency with the depth.

So, is the depth measured by the same coordinate as the cameras? BTW, it seems the quality of the depth is not very high. Why? Is the depth generated by COLMAP? If I would like to obtain a more accurate depth, do you suppose it is possible to re-estimate the depth with COLMAP, or reconstruct it and predict it via 3D methods like Gaussian Splatting?

Thanks!

**Comment by xiahongchi** [comment]
Hi!

You can check [wildrgbd_generate_point_cloud.py](https://github.com/wildrgbd/wildrgbd/blob/main/wildrgbd_generate_point_cloud.py) for the codes used to align cameras and depths.

The depth image is stored in millimeters, which is mentioned in [this](https://github.com/wildrgbd/wildrgbd/blob/6c16e9244477e09258b539d874b3c77fe1c530cd/wildrgbd_generate_point_cloud.py#L67)

**Comment by JiuTongBro** [comment]
Thanks. I will check it.
