### ISSUE TITLE
How many background scene are used in the dataset?

### ISSUE THREAD

**Issue by JiuTongBro** [wildrgbd/wildrgbd#5]
Hi! Thanks for your contribution of this valuable dataset!

However, I noticed that there are many replicated background used in different scenes. It seems you placed different objects in those scenarios to form different scene samples. So I wonder, as you created 20k scenes with 8.5k objects, how many different background scenarios are used in this dataset? Especially how any backgrounds are used to create the 'Single-Object' videos?

Thanks!

**Comment by xiahongchi** [comment]
Hi! Thanks for your interest in WildRGBD dataset.

We have different backgrounds throughout the whole dataset and they're various. But I'm sorry that I can't give you an exact number of total backgrounds.

Thanks!

Hongchi Xia

**Comment by JiuTongBro** [comment]
Thanks for your reply! But could you please give me a rough estimate of how many backgrounds there are, e.g. several hundreds? Thanks!

**Comment by xiahongchi** [comment]
Hi! Yea your estimation should be right. We roughly have over one hundred backgrounds in our dataset.

Thanks!

**Comment by JiuTongBro** [comment]
Got it. Thanks.
